[package]
name = "wiki-traverse"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
dotenvy = "0.15.7"
indicatif = "0.17.3"
nom = "7.1.3"
redis = "0.23.0"
serde_json = "1.0.96"
worker-pool = "0.2.1"
indexmap = "1.9.3"
rustc-hash = "1.1.0"
